[package]
name = "ptscan-tui"
version = "0.1.0"
authors = ["John-John Tedro <udoprog@tedro.se>"]
edition = "2018"
license = "MIT/Apache-2.0"
categories = ["data-structures"]

description = """
A terminal user interface to ptscan
"""

documentation = "https://docs.rs/ptscan"
homepage = "https://github.com/udoprog/ptscan"
repository = "https://github.com/udoprog/ptscan"

readme = "README.md"

[dependencies]
ptscan = {path = "../lib", version = "0.1.0"}
rayon = "1.0.3"
failure = "0.1.5"
hashbrown = "0.1.8"

[build-dependencies]
failure = "0.1"