include_guard = "ptscan_h"
language = "C++"

[export]
prefix = "pts_"
item_types = ["constants", "globals", "enums", "structs", "unions", "typedefs", "opaque", "functions"]

[export.rename]
"Address" = "address_t"
"Addresses" = "addresses_t"
"Type" = "type_t"
"Value" = "value_t"
"Values" = "values_t"
"StringT" = "string_t"
"Watch" = "watch_t"
"Scan" = "scan_t"
"Token" = "token_t"
"Pointer" = "pointer_t"
"ProcessHandle" = "process_handle_t"
"ThreadPool" = "thread_pool_t"
"SystemProcessesIter" = "system_processes_iter_t"
"ScanResult" = "scan_result_t"
"ScanResultsIter" = "scan_results_iter_t"
"ProcessId" = "process_id_t"
"Error" = "error_t"
"Filter" = "filter_t"
"ScanProgress" = "scan_progress_t"
"ScanProgressReportFn" = "scan_progress_report_fn"