name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release'
        required: true
        default: 'nightly'
        type: choice
        options:
        - nightly
        - "%date"
  push:
    tags:
      - '*'

env:
  KICK_VERSION: "%{git.tag} || ${{github.event.inputs.version}} || nightly"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
    - run: cargo run -p builder -- build --release
    - uses: udoprog/kick@nightly
    - run: kick msi --output dist
    - run: kick gh release --github-action --upload "dist/*"
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
