name: Release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
    steps:
    - uses: actions/checkout@v1
    - run: rustup toolchain install nightly --profile minimal
    - run: rustup default nightly
    - uses: actions-rs/cargo@v1
      with:
        command: x-builder
    - uses: softprops/action-gh-release@v1
      with:
        draft: true
        files: target/inno/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
